name: BoxSdkGen
options:
  bundleIdPrefix: box.com
targets:
  BoxSdkGen:
    scheme:
      configVariants:
    type: framework
    info:
      path: Sources/Info.plist
    platform: [macOS, iOS, tvOS, watchOS, visionOS]
    deploymentTarget:
      macOS: "10.15"
      iOS: "13.0"
      tvOS: "13.0"
      watchOS: "6.0"
      visionOS: "1.0"
    sources: [Sources]
    settings:
      PRODUCT_MODULE_NAME: BoxSdkGen

  # Tests for macOS
  BoxSdkGenTests_macOS:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: 10.15
    sources: [Tests]
    dependencies:
      - target: BoxSdkGen_macOS
    link: true
    settings:
      GENERATE_INFOPLIST_FILE: YES
      FRAMEWORK_SEARCH_PATHS: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      testPlans:
        - path: Tests/BoxSdkGenTests.xctestplan
          default: true
  
  # Tests for iOS
  BoxSdkGenTests_iOS:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 13.0
    sources: [Tests]
    dependencies:
      - target: BoxSdkGen_iOS
    link: true
    settings:
      GENERATE_INFOPLIST_FILE: YES
      FRAMEWORK_SEARCH_PATHS: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      testPlans:
        - path: Tests/BoxSdkGenTests.xctestplan
          default: true
  
  # Tests for tvOS
  BoxSdkGenTests_tvOS:
    type: bundle.unit-test
    platform: tvOS
    deploymentTarget: 13.0
    sources: [Tests]
    dependencies:
      - target: BoxSdkGen_tvOS
    link: true
    settings:
      GENERATE_INFOPLIST_FILE: YES
      FRAMEWORK_SEARCH_PATHS: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      testPlans:
        - path: Tests/BoxSdkGenTests.xctestplan
          default: true
  
  # Tests for watchOS
  BoxSdkGenTests_watchOS:
    type: bundle.unit-test
    platform: watchOS
    deploymentTarget: 6.0
    sources: [Tests]
    dependencies:
      - target: BoxSdkGen_watchOS
    link: true
    settings:
      GENERATE_INFOPLIST_FILE: YES
      FRAMEWORK_SEARCH_PATHS: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      testPlans:
        - path: Tests/BoxSdkGenTests.xctestplan
          default: true
  
  # Tests for visionOS
  BoxSdkGenTests_visionOS:
    type: bundle.unit-test
    platform: visionOS
    deploymentTarget: 1.0
    sources: [Tests]
    dependencies:
      - target: BoxSdkGen_visionOS
    link: true
    settings:
      GENERATE_INFOPLIST_FILE: YES
      FRAMEWORK_SEARCH_PATHS: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      testPlans:
        - path: Tests/BoxSdkGenTests.xctestplan
          default: true
  