ci_service: github
coverage_service: coveralls

xcodeproj: ./BoxSDKGen.xcodeproj
build_directory: build/DerivedData
scheme: BoxSDKGen_iOS
configuration: Debug

ignore:
  - Tests/*

output_directory: 'slather-report'
cobertura_xml: true
