name: BoxSdkGen
options:
  bundleIdPrefix: box.com
targets:
  BoxSdkGen:
    scheme:
      configVariants:
    type: framework
    info:
      path: Sources/Info.plist
    platform: [macOS, iOS, tvOS, watchOS, visionOS]
    deploymentTarget:
      macOS: "10.15"
      iOS: "13.0"
      tvOS: "13.0"
      watchOS: "6.0"
      visionOS: "1.0"
    sources: [Sources]