import Foundation

/// A standard representation of a signature request object.
public class SignRequestBase: Codable {
    private enum CodingKeys: String, CodingKey {
        case isDocumentPreparationNeeded = "is_document_preparation_needed"
        case redirectUrl = "redirect_url"
        case declinedRedirectUrl = "declined_redirect_url"
        case areTextSignaturesEnabled = "are_text_signatures_enabled"
        case emailSubject = "email_subject"
        case emailMessage = "email_message"
        case areRemindersEnabled = "are_reminders_enabled"
        case name
        case prefillTags = "prefill_tags"
        case daysValid = "days_valid"
        case externalId = "external_id"
        case templateId = "template_id"
        case externalSystemName = "external_system_name"
    }

    /// Indicates if the sender should receive a `prepare_url` in the response to complete document preparation using the UI.
    public let isDocumentPreparationNeeded: Bool?

    /// When specified, the signature request will be redirected to this url when a document is signed.
    @CodableTriState public private(set) var redirectUrl: String?

    /// The uri that a signer will be redirected to after declining to sign a document.
    @CodableTriState public private(set) var declinedRedirectUrl: String?

    /// Disables the usage of signatures generated by typing (text).
    public let areTextSignaturesEnabled: Bool?

    /// Subject of sign request email. This is cleaned by sign request. If this field is not passed, a default subject will be used.
    @CodableTriState public private(set) var emailSubject: String?

    /// Message to include in sign request email. The field is cleaned through sanitization of specific characters. However, some html tags are allowed. Links included in the message are also converted to hyperlinks in the email. The message may contain the following html tags including `a`, `abbr`, `acronym`, `b`, `blockquote`, `code`, `em`, `i`, `ul`, `li`, `ol`, and `strong`. Be aware that when the text to html ratio is too high, the email may end up in spam filters. Custom styles on these tags are not allowed. If this field is not passed, a default message will be used.
    @CodableTriState public private(set) var emailMessage: String?

    /// Reminds signers to sign a document on day 3, 8, 13 and 18. Reminders are only sent to outstanding signers.
    public let areRemindersEnabled: Bool?

    /// Name of the signature request.
    public let name: String?

    /// When a document contains sign-related tags in the content, you can prefill them using this `prefill_tags` by referencing the 'id' of the tag as the `external_id` field of the prefill tag.
    public let prefillTags: [SignRequestPrefillTag]?

    /// Set the number of days after which the created signature request will automatically expire if not completed. By default, we do not apply any expiration date on signature requests, and the signature request does not expire.
    @CodableTriState public private(set) var daysValid: Int64?

    /// This can be used to reference an ID in an external system that the sign request is related to.
    @CodableTriState public private(set) var externalId: String?

    /// When a signature request is created from a template this field will indicate the id of that template.
    @CodableTriState public private(set) var templateId: String?

    /// Used as an optional system name to appear in the signature log next to the signers who have been assigned the `embed_url_external_id`.
    @CodableTriState public private(set) var externalSystemName: String?

    /// Initializer for a SignRequestBase.
    ///
    /// - Parameters:
    ///   - isDocumentPreparationNeeded: Indicates if the sender should receive a `prepare_url` in the response to complete document preparation using the UI.
    ///   - redirectUrl: When specified, the signature request will be redirected to this url when a document is signed.
    ///   - declinedRedirectUrl: The uri that a signer will be redirected to after declining to sign a document.
    ///   - areTextSignaturesEnabled: Disables the usage of signatures generated by typing (text).
    ///   - emailSubject: Subject of sign request email. This is cleaned by sign request. If this field is not passed, a default subject will be used.
    ///   - emailMessage: Message to include in sign request email. The field is cleaned through sanitization of specific characters. However, some html tags are allowed. Links included in the message are also converted to hyperlinks in the email. The message may contain the following html tags including `a`, `abbr`, `acronym`, `b`, `blockquote`, `code`, `em`, `i`, `ul`, `li`, `ol`, and `strong`. Be aware that when the text to html ratio is too high, the email may end up in spam filters. Custom styles on these tags are not allowed. If this field is not passed, a default message will be used.
    ///   - areRemindersEnabled: Reminds signers to sign a document on day 3, 8, 13 and 18. Reminders are only sent to outstanding signers.
    ///   - name: Name of the signature request.
    ///   - prefillTags: When a document contains sign-related tags in the content, you can prefill them using this `prefill_tags` by referencing the 'id' of the tag as the `external_id` field of the prefill tag.
    ///   - daysValid: Set the number of days after which the created signature request will automatically expire if not completed. By default, we do not apply any expiration date on signature requests, and the signature request does not expire.
    ///   - externalId: This can be used to reference an ID in an external system that the sign request is related to.
    ///   - templateId: When a signature request is created from a template this field will indicate the id of that template.
    ///   - externalSystemName: Used as an optional system name to appear in the signature log next to the signers who have been assigned the `embed_url_external_id`.
    public init(isDocumentPreparationNeeded: Bool? = nil, redirectUrl: TriStateField<String> = nil, declinedRedirectUrl: TriStateField<String> = nil, areTextSignaturesEnabled: Bool? = nil, emailSubject: TriStateField<String> = nil, emailMessage: TriStateField<String> = nil, areRemindersEnabled: Bool? = nil, name: String? = nil, prefillTags: [SignRequestPrefillTag]? = nil, daysValid: TriStateField<Int64> = nil, externalId: TriStateField<String> = nil, templateId: TriStateField<String> = nil, externalSystemName: TriStateField<String> = nil) {
        self.isDocumentPreparationNeeded = isDocumentPreparationNeeded
        self._redirectUrl = CodableTriState(state: redirectUrl)
        self._declinedRedirectUrl = CodableTriState(state: declinedRedirectUrl)
        self.areTextSignaturesEnabled = areTextSignaturesEnabled
        self._emailSubject = CodableTriState(state: emailSubject)
        self._emailMessage = CodableTriState(state: emailMessage)
        self.areRemindersEnabled = areRemindersEnabled
        self.name = name
        self.prefillTags = prefillTags
        self._daysValid = CodableTriState(state: daysValid)
        self._externalId = CodableTriState(state: externalId)
        self._templateId = CodableTriState(state: templateId)
        self._externalSystemName = CodableTriState(state: externalSystemName)
    }

    required public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        isDocumentPreparationNeeded = try container.decodeIfPresent(Bool.self, forKey: .isDocumentPreparationNeeded)
        redirectUrl = try container.decodeIfPresent(String.self, forKey: .redirectUrl)
        declinedRedirectUrl = try container.decodeIfPresent(String.self, forKey: .declinedRedirectUrl)
        areTextSignaturesEnabled = try container.decodeIfPresent(Bool.self, forKey: .areTextSignaturesEnabled)
        emailSubject = try container.decodeIfPresent(String.self, forKey: .emailSubject)
        emailMessage = try container.decodeIfPresent(String.self, forKey: .emailMessage)
        areRemindersEnabled = try container.decodeIfPresent(Bool.self, forKey: .areRemindersEnabled)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        prefillTags = try container.decodeIfPresent([SignRequestPrefillTag].self, forKey: .prefillTags)
        daysValid = try container.decodeIfPresent(Int64.self, forKey: .daysValid)
        externalId = try container.decodeIfPresent(String.self, forKey: .externalId)
        templateId = try container.decodeIfPresent(String.self, forKey: .templateId)
        externalSystemName = try container.decodeIfPresent(String.self, forKey: .externalSystemName)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isDocumentPreparationNeeded, forKey: .isDocumentPreparationNeeded)
        try container.encode(field: _redirectUrl.state, forKey: .redirectUrl)
        try container.encode(field: _declinedRedirectUrl.state, forKey: .declinedRedirectUrl)
        try container.encodeIfPresent(areTextSignaturesEnabled, forKey: .areTextSignaturesEnabled)
        try container.encode(field: _emailSubject.state, forKey: .emailSubject)
        try container.encode(field: _emailMessage.state, forKey: .emailMessage)
        try container.encodeIfPresent(areRemindersEnabled, forKey: .areRemindersEnabled)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(prefillTags, forKey: .prefillTags)
        try container.encode(field: _daysValid.state, forKey: .daysValid)
        try container.encode(field: _externalId.state, forKey: .externalId)
        try container.encode(field: _templateId.state, forKey: .templateId)
        try container.encode(field: _externalSystemName.state, forKey: .externalSystemName)
    }

}
