#!/bin/sh

if [[ "$#" -ne 1 ]]; then
    echo "Illegal number of parameters"
    return 1
fi

DEVELOPER_TOKEN=$1
INT_TEST_CONFIG_PATH="IntegrationTests/Configuration.swift"

sed -i.bak -E "s|(.*developerToken.*= \")(.*)(\".*)|\1${DEVELOPER_TOKEN}\3|g" "${INT_TEST_CONFIG_PATH}"
rm "${INT_TEST_CONFIG_PATH}.bak"