name: Build and Test
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macos-13
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14']
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
      - name: List Xcode available versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup carthage dependencies
        working-directory: BoxSDK
        run: ./scripts/bootstrap
      - name: Lint
        working-directory: BoxSDK
        run: swiftlint
      - name: Run unit tests
        working-directory: BoxSDK
        run: set -o pipefail && xcodebuild -workspace BoxSDK.xcworkspace -scheme BoxSDK-iOS -destination "${{ matrix.destination }}" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES -enableCodeCoverage YES test
      - name: Extract branch name
        working-directory: BoxSDK
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - run: bundle exec slather
        working-directory: BoxSDK
        env:
          GIT_BRANCH: ${{ steps.get_branch.outputs.branch }}
          CI_PULL_REQUEST: ${{ github.event.number }}
          COVERAGE_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
